final Map<String, String> states = {
  "SP": 'São Paulo',
  "RJ": "Rio de Janeiro",
  "MG": 'Minas Gerais',
  "ES": 'Espírito Santo',
  "AC": 'Acre',
  "AL": 'Alagoas',
  "AP": 'Amapá',
  "AM": 'Amazonas',
  "BA": 'Bahia',
  "CE": 'Ceará',
  "DF": 'Distrito Federal',
  "GO": 'Goiás',
  "MA": 'Maranhão',
  "MT": 'Mato Grosso',
  "MS": 'Mato Grosso do Sul',
  "PA": 'Pará',
  "PB": 'Paraíba',
  "PR": 'Paraná',
  "PE": 'Pernambuco',
  "PI": 'Piauí',
  "RN": 'Rio Grande do Norte',
  "RS": 'Rio Grande do Sul',
  "RO": 'Rondônia',
  "RR": 'Roraima',
  "SC": 'Santa Catarina',
  "SE": 'Sergipe',
  "TO": 'Tocantins',
};
